name: Container Processing

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get tag
      id: get_tag
      run: |
        echo "::set-output name=IMAGE_TAG::$(echo $GITHUB_REF | cut -d / -f 3)"
    
    - name: Set up qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ vars.DOCKER_USERNAME }}" --password-stdin

    - name: Get changes
      id: identify
      uses: jitterbit/get-changed-files@v1
    - run: |
        echo ${{ steps.files.output.all }}

    - name: Build image
      env: 
        # The owner and repository name (for example,
        # iqtlabs/edgetech-daisy), and repository token
        GITHUB_OWNER_REPO: ${{ github.repository }}
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

        # Directiory containing the Dockerfile, and Docker namespace
        DOCKER_FOLDER: "axis-ptz-controller"
        DOCKER_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}

      run: |
        GITHUB_REPO=$(basename $GITHUB_OWNER_REPO)
        echo ${DOCKER_NAMESPACE}/$GITHUB_REPO:latest \
        echo $DOCKER_NAMESPACE/$GITHUB_REPO:${{ steps.get_tag.outputs.IMAGE_TAG }}
#          docker buildx build "$folder" --push \
#          --tag $DOCKER_NAMESPACE/$PUBLISHNAME:latest \
#          --tag $DOCKER_NAMESPACE/$PUBLISHNAME:${{ steps.get_tag.outputs.IMAGE_TAG }} \
#          --platform linux/arm64,linux/amd64 
