name: Container Build Testing

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Build Check
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Get changes
      id: identify
      uses: jitterbit/get-changed-files@v1
    - run: |
        echo ${{ steps.files.output.all }}

    - name: Build image
      env: 
        DOCKER_FOLDER: "axis-ptz-controller"
      run: |
        docker buildx build $DOCKER_FOLDER \
        --platform linux/arm64,linux/amd64
